// client/src/components/common/button/ButtonBase.vue
<template>
    <button :class="buttonClass" @click="$emit('onClick')">
        <i v-if="iconClass" :class="iconClass"></i>
        {{ text }}
    </button>
</template>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { BUTTON_KEY as KEY } from "@/constants/keyConstants";
import { BUTTON_CONFIGS } from "@/constants/uiConstants";
import { ButtonConfig } from "@/types/buttonTypes";

export default defineComponent({
    name: "ButtonBase",
    props: {
        action: { type: String, required: true },
    },
    setup(props) {
        const buttonConfig = computed<ButtonConfig | undefined>(() =>
            BUTTON_CONFIGS.find((config) => config[KEY.ACTION] === props.action)
        );

        const buttonClass = computed(() => `button-${props.action}`);
        const iconClass = computed(() => buttonConfig.value?.[KEY.ICON_CLASS]);
        const text = computed(() => buttonConfig.value?.[KEY.TEXT]);

        return { buttonClass, iconClass, text };
    },
});
</script>

<style></style>

// haenam-next/components/common/button/ButtonBase.tsx
"use client";

import { ButtonProps } from "@/types/button";
import { BUTTON_KEY as KEY } from "@/constants/keyConstants";
import { BUTTON_CONFIGS } from "@/constants/uiConstants";

export default function ButtonBase({
    action,
    className,
    onClick = () => {},
}: ButtonProps) {
    const config = BUTTON_CONFIGS.find(
        (config) => config[KEY.ACTION] === action,
    );

    if (!config) {
        console.error("Button is not defined");
        return null;
    }

    const buttonClass = `button-${action} ${className}`;
    const iconClass = config[KEY.ICON_CLASS];
    const text = config[KEY.TEXT];

    return (
        <button className={buttonClass} onClick={onClick}>
            {iconClass && <i className={iconClass}></i>}
            {text}
        </button>
    );
}
